public class NewAndExistingAccountController {
    
    public PageReference save() {
        try {
            upsert(account);
        }
        catch (System.DMLException e)
        {
            ApexPages.addMessages(e);
            return null;
        }
        PageReference redirectSuccess = new ApexPages.StandardController(Account).view();
        return redirectSuccess;
    }
    
    public Account account {get; private set;}
    
    public NewAndExistingAccountController() {
        Id id = ApexPages.currentPage().getParameters().get('id');
        account = (id == null)?new Account():[select name, phone, industry from Account where id=:id];
    }
}